package model

import (
	"invest/utils"
	"time"
)

var DefaultGantaParent1 = Ganta {
	IsAdditional:  false,
	ProjectId:     0,  // will be set
	Kaz:           "Пакет документов предоставляемый Инициатором проекта на первом этапе",
	Rus:           "Пакет документов предоставляемый Инициатором проекта на первом этапе",
	Eng:           "Пакет документов предоставляемый Инициатором проекта на первом этапе",
	StartDate:     utils.GetCurrentTime(),
	DurationInDays:      10,
	GantaParentId: 0,
	Status:        utils.ProjectStatusInprogress,
}

var DefaultGantaParent2 = Ganta{
	IsAdditional:  false,
	Kaz:           "Пакет документов предоставляемый Инициатором проекта на втором этапе",
	Rus:           "Пакет документов предоставляемый Инициатором проекта на втором этапе",
	Eng:           "Пакет документов предоставляемый Инициатором проекта на втором этапе",
	StartDate:     utils.GetCurrentTime().Add(time.Hour * 24 * 10),
	DurationInDays:      10,
	GantaParentId: 0,
	Status:        utils.ProjectStatusInprogress,
}

var DefaultGantaChildren1 = []Ganta{
	{
		IsAdditional:  false,
		Kaz:           "Свидетельство/справка о государственной регистрации юридического лица",
		Rus:           "Свидетельство/справка о государственной регистрации юридического лица",
		Eng:           "Свидетельство/справка о государственной регистрации юридического лица",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,			// will be set
		Status:        utils.ProjectStatusInprogress,			// this status will not be considered instead consider the status of the child
	},
	{
		IsAdditional:  false,
		Kaz:           "Устав, Учредительный договор",
		Rus:           "Устав, Учредительный договор",
		Eng:           "Устав, Учредительный договор",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Решение Уполномоченного органа юридического лица о назначении исполнительного органа",
		Rus:           "Решение Уполномоченного органа юридического лица о назначении исполнительного органа",
		Eng:           "Решение Уполномоченного органа юридического лица о назначении исполнительного органа",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Копии документов, удостоверяющих личность руководителя, главного бухгалтера предприятия, всех учредителей предприятия, владеющих более 10% уставного капитала;",
		Rus:           "Копии документов, удостоверяющих личность руководителя, главного бухгалтера предприятия, всех учредителей предприятия, владеющих более 10% уставного капитала;",
		Eng:           "Копии документов, удостоверяющих личность руководителя, главного бухгалтера предприятия, всех учредителей предприятия, владеющих более 10% уставного капитала;",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Документы, подтверждающие наличие денежных средств для реализации проекта",
		Rus:           "Документы, подтверждающие наличие денежных средств для реализации проекта",
		Eng:           "Документы, подтверждающие наличие денежных средств для реализации проекта",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 		0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Отчет Первого кредитного бюро",
		Rus:           "Отчет Первого кредитного бюро",
		Eng:           "Отчет Первого кредитного бюро",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Справку из государственного органа об отсутствии задолженности по налогам и обязательным платежам в бюджет, либо акт сверки",
		Rus:           "Справку из государственного органа об отсутствии задолженности по налогам и обязательным nплатежам в бюджет, либо акт сверки",
		Eng:           "Справку из государственного органа об отсутствии задолженности по налогам и обязательным nплатежам в бюджет, либо акт сверки",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Бизнес – план согласно Инструкции по составлению бизнес – плана инвестиционного проекта СПК (на бумажном и электронном носителях), паспорт проекта",
		Rus:           "Бизнес – план согласно Инструкции по составлению бизнес – плана инвестиционного проекта СПК (на бумажном и электронном носителях), паспорт проекта",
		Eng:           "Бизнес – план согласно Инструкции по составлению бизнес – плана инвестиционного проекта СПК (на бумажном и электронном носителях), паспорт проекта",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Документы, удостоверяющие право собственности на имущество, передаваемое в совместный с СПК проект (при наличии)",
		Rus:           "Документы, удостоверяющие право собственности на имущество, передаваемое в совместный с СПК проект (при наличии)",
		Eng:           "Документы, удостоверяющие право собственности на имущество, передаваемое в совместный с СПК проект (при наличии)",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Справка об отсутствии обременения на имущество, передаваемое в совместный с СПК проект (при наличии)",
		Rus:           "Справка об отсутствии обременения на имущество, передаваемое в совместный с СПК проект (при наличии)",
		Eng:           "Справка об отсутствии обременения на имущество, передаваемое в совместный с СПК проект (при наличии)",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},

	{
		IsAdditional:  false,
		Kaz:           "Копия договоров займов (при наличии)",
		Rus:           "Копия договоров займов (при наличии)",
		Eng:           "Копия договоров займов (при наличии)",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
	{
		IsAdditional:  false,
		Kaz:           "Форэскиз (по необходимости)",
		Rus:           "Форэскиз (по необходимости)",
		Eng:           "Форэскиз (по необходимости)",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        utils.ProjectStatusInprogress,
	},
}

var DefaultGantaChildren2 = []Ganta{
	{
		IsAdditional:  false,
		Kaz:           "Проспект выпуска акций, Выписка из реестра акционеров, Отчет об итогах выпуска эмиссии акций, уведомление об утверждении отчета об итогах размещения акций, Свидетельство о регистрации выпуска ценных бумаг, Договор с реестродержателем (независимым регистратором) - для акционерных обществ",
		Rus:           "Проспект выпуска акций, Выписка из реестра акционеров, Отчет об итогах выпуска эмиссии акций, уведомление об утверждении отчета об итогах размещения акций, Свидетельство о регистрации выпуска ценных бумаг, Договор с реестродержателем (независимым регистратором) - для акционерных обществ",
		Eng:           "Проспект выпуска акций, Выписка из реестра акционеров, Отчет об итогах выпуска эмиссии акций, уведомление об утверждении отчета об итогах размещения акций, Свидетельство о регистрации выпуска ценных бумаг, Договор с реестродержателем (независимым регистратором) - для акционерных обществ",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,			// will be set
		Status:        "",			// this status will not be considered instead consider the status of the child
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Документы, подтверждающие формирование уставного капитала (для хозяйственного товарищества)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Лицензия – если вид деятельности лицензируемый",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Карточка с образцами подписей и оттиском печати (нотариально заверенная)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},

	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Копия финансовой отчетности предприятия за последние 3 отчетных года с приложением копий налоговых деклараций с приложением расшифровки",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Расшифровка основных статей баланса: дебиторской и кредиторской задолженностей с указанием источника, условий и даты возникновения, основных средств, сырья, материалов, готовой продукции",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},

	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Справка обслуживающего банка об оборотах за последние двенадцать месяцев, с указанием входящего и исходящего остатка денег на начало и конец периода",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Сведения о счетах в Банках, сведения о наличии/ отсутствии ссудной задолженности и картотеки No2",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Отчет Первого кредитного бюро (обновленный, на текущую дату)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Справку из государственного органа об отсутствии задолженности по налогам и обязательным платежам в бюджет, либо акт сверки. (обновленную на текущую дату)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Другие документы (действующие контракты, финансовые документы и т.д.) запрашиваются менеджером проекта в ходе рассмотрения проекта",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Бизнес – план согласно Инструкции по составлению бизнес – плана инвестиционного проекта СПК (на бумажном и электронном носителях), паспорт проекта (с корректировкой на текущую дату)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Отчет об оценке имущества, передаваемого в совместный с СПК проект",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
	{
		IsAdditional:  false,
		Kaz:           "",
		Rus:           "Информация по аффилированным компаниям (акционера, первого руководителя)",
		Eng:           "",
		StartDate:     utils.GetCurrentTime(),
		DurationInDays:      3,
		GantaParentId: 0,
		Status:        "",
	},
}
