version: '3.5'

services:
  postgres:
    restart: always
    env_file:
      - environment/local.env
    image: postgres:11
    volumes:
      - "/docker_volumes/spk/postgre:/var/lib/postgresql/data"
    networks:
      - network
    environment:
      - "TZ=Asia/Almaty"
    #    container_name: "postgres_spk"
    ports:
      - "$HOST:7001:5432"
#    hostname: "spk_postgres"

  redis:
    restart: always
    image: redis:5.0
    #    command: redis-server --requirepass f5db003759b2456f8acb
    volumes:
      - "/docker_volumes/spk/data"
    environment:
      - "TZ=Asia/Almaty"
    env_file:
      - environment/local.env
    networks:
      - network
    ports:
      - "$HOST:7002:6379"
#    hostname: "spk_redis"

networks:
  network:
    driver: bridge



